services:
  db:
    image: postgres:16
    container_name: pg-producao
    environment:
      POSTGRES_DB: producao_db
      POSTGRES_USER: producao_user
      POSTGRES_PASSWORD: producao_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
